services:
  versaproject.api:
    image: versaproject.api
    build:
      context: .
      dockerfile: VersaProject.Api/Dockerfile
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASESETTINGS__USERID}
      POSTGRES_PASSWORD: ${DATABASESETTINGS__PASSWORD}
      POSTGRES_DB: ${DATABASESETTINGS__DATABASE}
    ports:
      - "15432:5432"