services:
  versaproject.api:
    depends_on: 
      - database
    image: anjelikalika/versaproject.api
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    ports:
      - "8080:8080"
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASESETTINGS__USERID}
      POSTGRES_PASSWORD: ${DATABASESETTINGS__PASSWORD}
      POSTGRES_DB: ${DATABASESETTINGS__DATABASE}
    ports:
      - "15432:5432"
